# -*- coding: utf-8 -*-
"""Predictive Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VdDgLW9Sd5QUS5JLvULj46Pfh5KkKwy
"""

import pandas as pd

# Load dataset
data = pd.read_csv("ghana_weather_final.csv")

# Preview
data.head()

# Sorting properly
data = data.sort_values(by=['Year', 'Month_Num'])

# Create lag (previous month's rainfall)
data['Rainfall_Lag1'] = data['Rainfall_mm'].shift(1)

# Drop first row (lag is NaN)
data = data.dropna()

data.head()

# TRAINING MODEL WITH LAG
# ---------------------------------------------------

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Features
X = data[['Avg_Temp', 'Month_Num', 'Year', 'Rainfall_Lag1']]

# Target
y = data['Rainfall_mm']

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train
model = LinearRegression()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
r2 = r2_score(y_test, y_pred)
import numpy as np

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("R2:", r2)
print("RMSE:", rmse)

# CREATING 2040 DATA


future_2040 = pd.DataFrame({
    'Year': [2040]*12,
    'Month_Num': list(range(1, 13))
})

future_2040.head(10)

# Monthly average temperature
monthly_temp_avg = data.groupby('Month_Num')['Avg_Temp'].mean().reset_index()

future_2040 = future_2040.merge(monthly_temp_avg, on='Month_Num', how='left')

future_2040['Rainfall_Lag1'] = 0
future_2040['Predicted_Rainfall'] = 0

# RECURSIVE PREDICTION FOR 2040


for i in range(len(future_2040)):

    # January → use last real rainfall from dataset
    if i == 0:
        last_rainfall = data.iloc[-1]['Rainfall_mm']
        future_2040.loc[i, 'Rainfall_Lag1'] = last_rainfall
    else:
        # Use previous predicted rainfall
        future_2040.loc[i, 'Rainfall_Lag1'] = future_2040.loc[i-1, 'Predicted_Rainfall']

    # Prepare input
    X_future = future_2040.loc[i, ['Avg_Temp', 'Month_Num', 'Year', 'Rainfall_Lag1']].values.reshape(1, -1)

    # Predict
    prediction = model.predict(X_future)

    # Store result
    future_2040.loc[i, 'Predicted_Rainfall'] = prediction[0]

future_2040

future_2040.head(12)

import matplotlib.pyplot as plt

plt.figure()

plt.plot(future_2040['Month_Num'], future_2040['Predicted_Rainfall'], marker='o')

plt.title("Predicted Monthly Rainfall for 2040 (With Lag)")
plt.xlabel("Month")
plt.ylabel("Rainfall (mm)")

plt.xticks(range(1,18))
plt.grid()

plt.show()